define("discourse/plugins/discourse-lazy-videos/discourse/components/lazy-iframe",["exports","@glimmer/component","@ember/component","@ember/template-factory"],function(e,t,i,o){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
class s extends t.default{get iframeSrc(){switch(this.args.providerName){case"youtube":let e=`https://www.youtube.com/embed/${this.args.videoId}?autoplay=1&rel=0`
return this.args.startTime&&(e+=`&start=${function(e){const t=e.toString().match(/(?:(\d+)h)?(?:(\d+)m)?(?:(\d+)s)?/),[i,o,s]=t.slice(1)
if(i||o||s)return 3600*(parseInt(i,10)||0)+60*(parseInt(o,10)||0)+(parseInt(s,10)||0)
return e}(this.args.startTime)}`),e
case"vimeo":return`https://player.vimeo.com/video/${this.args.videoId}${this.args.videoId.includes("?")?"&":"?"}autoplay=1`
case"tiktok":return`https://www.tiktok.com/embed/v2/${this.args.videoId}`}}static{(0,i.setComponentTemplate)((0,o.createTemplateFactory)({id:"z9eqHglx",block:'[[[41,[30,1],[[[1,"  "],[10,"iframe"],[15,"src",[30,0,["iframeSrc"]]],[15,"title",[30,2]],[14,"allowFullScreen",""],[14,"scrolling","no"],[14,"frameborder","0"],[14,"seamless","seamless"],[14,"allow","accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"],[12],[13],[1,"\\n"]],[]],null]],["@providerName","@title"],["if"]]',moduleName:"/var/www/discourse/frontend/discourse/discourse/plugins/discourse-lazy-videos/discourse/components/lazy-iframe.js",isStrictMode:!0}),this)}}e.default=s}),define("discourse/plugins/discourse-lazy-videos/discourse/components/lazy-video",["exports","@glimmer/component","@glimmer/tracking","@ember/helper","@ember/modifier","@ember/object","@ember/template","discourse/helpers/concat-class","discourse-i18n","discourse/plugins/discourse-lazy-videos/discourse/components/lazy-iframe","@ember/component","@ember/template-factory"],function(e,t,i,o,s,r,a,d,n,l,c,u){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
class m extends t.default{static{dt7948.g(this.prototype,"isLoaded",[i.tracked],function(){return!1})}#e=void dt7948.i(this,"isLoaded")
get thumbnailStyle(){const e=this.args.videoAttributes.dominantColor
if(e?.match(/^[0-9A-Fa-f]+$/))return(0,a.htmlSafe)(`background-color: #${e};`)}loadEmbed(){this.isLoaded||(this.isLoaded=!0,this.args.onLoadedVideo?.())}static{dt7948.n(this.prototype,"loadEmbed",[r.action])}onKeyPress(e){"Enter"!==e.key&&" "!==e.key||(e.preventDefault(),this.loadEmbed())}static{dt7948.n(this.prototype,"onKeyPress",[r.action])}static{(0,c.setComponentTemplate)((0,u.createTemplateFactory)({id:"Zvje7dic",block:'[[[10,0],[15,"data-video-id",[30,1,["id"]]],[15,"data-video-title",[30,1,["title"]]],[15,"data-video-start-time",[30,1,["startTime"]]],[15,"data-provider-name",[30,1,["providerName"]]],[15,0,[28,[32,0],["lazy-video-container",[28,[32,1],[[30,1,["providerName"]],"-onebox"],null],[52,[30,0,["isLoaded"]],"video-loaded"]],null]],[12],[1,"\\n"],[41,[30,0,["isLoaded"]],[[[1,"    "],[8,[32,2],null,[["@providerName","@title","@videoId","@startTime"],[[30,1,["providerName"]],[30,1,["title"]],[30,1,["id"]],[30,1,["startTime"]]]],null],[1,"\\n"]],[]],[[[1,"    "],[11,0],[24,"role","button"],[24,"tabindex","0"],[16,"aria-label",[28,[32,3],["lazy_videos.play_video"],[["title"],[[30,1,["title"]]]]]],[16,5,[30,0,["thumbnailStyle"]]],[16,0,[28,[32,0],["video-thumbnail",[30,1,["providerName"]]],null]],[4,[32,4],["click",[30,0,["loadEmbed"]]],null],[4,[32,4],["keypress",[30,0,["onKeyPress"]]],null],[12],[1,"\\n      "],[10,"img"],[15,"src",[30,1,["thumbnail"]]],[15,"title",[30,1,["title"]]],[14,"loading","lazy"],[15,0,[28,[32,1],[[30,1,["providerName"]],"-thumbnail"],null]],[12],[13],[1,"\\n      "],[10,0],[15,0,[28,[32,0],["icon",[28,[32,1],[[30,1,["providerName"]],"-icon"],null]],null]],[12],[13],[1,"\\n    "],[13],[1,"\\n    "],[10,0],[14,0,"title-container"],[12],[1,"\\n      "],[10,0],[14,0,"title-wrapper"],[12],[1,"\\n        "],[10,3],[15,6,[30,1,["url"]]],[15,"title",[30,1,["title"]]],[14,"target","_blank"],[14,"rel","noopener noreferrer"],[14,0,"title-link"],[12],[1,"\\n          "],[1,[30,1,["title"]]],[1,"\\n        "],[13],[1,"\\n      "],[13],[1,"\\n    "],[13],[1,"\\n"]],[]]],[13]],["@videoAttributes"],["if"]]',moduleName:"/var/www/discourse/frontend/discourse/discourse/plugins/discourse-lazy-videos/discourse/components/lazy-video.js",scope:()=>[d.default,o.concat,l.default,n.i18n,s.on],isStrictMode:!0}),this)}}e.default=m}),define("discourse/plugins/discourse-lazy-videos/discourse/initializers/lazy-videos-admin-plugin-configuration-nav",["exports","discourse/lib/plugin-api"],function(e,t){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
e.default={name:"lazy-videos-admin-plugin-configuration-nav",initialize(e){const i=e.lookup("service:current-user")
i?.admin&&(0,t.withPluginApi)(e=>{e.setAdminPluginIcon("discourse-lazy-videos","bed")})}}}),define("discourse/plugins/discourse-lazy-videos/initializers/lazy-videos",["exports","discourse/lib/plugin-api","discourse/plugins/discourse-lazy-videos/discourse/components/lazy-video","discourse/plugins/discourse-lazy-videos/lib/lazy-video-attributes","@ember/component","@ember/template-factory","@ember/component/template-only"],function(e,t,i,o,s,r,a){"use strict"
function d(e){e.decorateCookedElement((t,d)=>{if(t.classList.contains("d-editor-preview"))return
t.querySelectorAll(".lazy-video-container").forEach(n=>{const l=e.container.lookup("service:site-settings"),c=(0,o.default)(n)
if(l[`lazy_${c.providerName}_enabled`]){const o=()=>{const i=t.closest("article")?.dataset?.postId
i&&e.preventCloak(parseInt(i,10))},l=document.createElement("p")
l.classList.add("lazy-video-wrapper"),d.renderGlimmer(l,(0,s.setComponentTemplate)((0,r.createTemplateFactory)({id:"DNGyViyk",block:'[[[8,[32,0],null,[["@videoAttributes","@onLoadedVideo"],[[30,1,["param"]],[30,1,["onLoadedVideo"]]]],null]],["@data"],[]]',moduleName:"/var/www/discourse/frontend/discourse/discourse/plugins/discourse-lazy-videos/initializers/lazy-videos.js",scope:()=>[i.default],isStrictMode:!0}),(0,a.default)(void 0,void 0)),{param:c,onLoadedVideo:o}),n.replaceWith(l)}})},{onlyStream:!0})}Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
e.default={name:"discourse-lazy-videos",initialize(){(0,t.withPluginApi)(d)}}}),define("discourse/plugins/discourse-lazy-videos/lib/lazy-video-attributes",["exports"],function(e){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=function(e){if(!e.classList.contains("lazy-video-container"))return{}
const t=e.querySelector("a")?.getAttribute("href"),i=e.querySelector("img"),o=i?.getAttribute("src"),s=i?.dataset?.dominantColor,r=e.dataset.videoTitle,a=e.dataset.videoStartTime,d=e.dataset.providerName,n=e.dataset.videoId
return{url:t,thumbnail:o,title:r,providerName:d,id:n,dominantColor:s,startTime:a}}})

//# sourceMappingURL=discourse-lazy-videos-9ceefd58.map